name: timezone
version: 0.6.1
authors:
- Boris Kaul <localvoid@gmail.com>
- Sam Rawlins <sam.rawlins@gmail.com>
description: Time zone database and time zone aware DateTime.
homepage: https://github.com/srawlins/timezone
environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'
dependencies:
  path: '^1.3.0'
dev_dependencies:
  args: any
  file: ^6.0.0-nullsafety
  glob: ^2.0.0-nullsafety
  logging: ^1.0.0-nullsafety.0
  pedantic: ^1.9.0
  test: ^1.16.0-nullsafety.13

dependency_overrides:
  args:
    git: https://github.com/dart-lang/args.git
  glob:
    git: https://github.com/dart-lang/glob.git
  logging: ^1.0.0-nullsafety.0
